<a href="https://colab.research.google.com/github/2403a52026-lgtm/NLP.LabAssignments/blob/main/NLP_assignment_17_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers
!pip install sentencepiece
!pip install torch
!pip install pandas

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from transformers import pipeline
import pandas as pd

In [3]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

class CustomTranslator:
    def __init__(self, model_name):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    def __call__(self, text):
        inputs = self.tokenizer(text, return_tensors="pt", padding=True)
        # A default max_length is used, it can be adjusted if needed.
        outputs = self.model.generate(**inputs, max_length=512)
        translated_text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        return [{"translation_text": translated_text}]

translator_fr = CustomTranslator("Helsinki-NLP/opus-mt-en-fr")
translator_de = CustomTranslator("Helsinki-NLP/opus-mt-en-de")
translator_hi = CustomTranslator("Helsinki-NLP/opus-mt-en-hi")

print("Models Loaded Successfully")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/768k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/298M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/298M [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/812k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/1.07M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/306M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/306M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

Models Loaded Successfully

In [ ]:
df = pd.read_csv("translation_dataset.csv")
df

,id,category,sentence_type,english_sentence
0,1,News,Simple,The government announced a new education polic...
1,2,News,Compound,The minister spoke to the media and explained ...
2,3,News,Complex,"Although the economy is growing, unemployment ..."
3,4,Social Media,Conversational,I just watched a great movie and I loved it.
4,5,Social Media,Interrogative,Did you complete the assignment for NLP class?
5,6,Social Media,Simple,Learning Python is fun and interesting.
6,7,Academic,Technical,Machine learning models require large amounts ...
7,8,Academic,Complex,"When neural networks are trained properly, the..."
8,9,Academic,Compound,Natural language processing is useful and it i...
9,10,Conversation,Simple,Please close the door.
10,11,Conversation,Interrogative,Where are you going now?
11,12,Conversation,Compound,I will call you later and we can discuss the p...
12,13,Technical,Technical,The transformer model uses attention mechanism...
13,14,Technical,Complex,"If the dataset is clean, the model will produc..."
14,15,Daily Life,Simple,I am going to the market.
15,16,Daily Life,Interrogative,Can you help me with this problem?
16,17,Daily Life,Complex,"Even though it was raining, we went to college."
17,18,News,Technical,Scientists discovered a new satellite in space.
18,19,Academic,Complex,"While studying NLP, students learn about token..."
19,20,Conversation,Conversational,Let us meet tomorrow and finish the work.

In [ ]:
sentences = df["english_sentence"].tolist()

print(sentences[:5])

['The government announced a new education policy today.', 'The minister spoke to the media and explained the new reforms.', 'Although the economy is growing, unemployment remains a concern.', 'I just watched a great movie and I loved it.', 'Did you complete the assignment for NLP class?']

In [ ]:
french_translations = []

for sentence in sentences:
    translated = translator_fr(sentence)[0]['translation_text']
    french_translations.append(translated)

df["French"] = french_translations

df.head()

,id,category,sentence_type,english_sentence,French
0,1,News,Simple,The government announced a new education polic...,Le gouvernement a annoncé aujourd'hui une nouv...
1,2,News,Compound,The minister spoke to the media and explained ...,Le ministre s'est entretenu avec les médias et...
2,3,News,Complex,"Although the economy is growing, unemployment ...","Bien que l'économie se développe, le chômage d..."
3,4,Social Media,Conversational,I just watched a great movie and I loved it.,Je viens de regarder un super film et j'ai adoré.
4,5,Social Media,Interrogative,Did you complete the assignment for NLP class?,Avez-vous terminé l'affectation pour la classe...

In [ ]:
german_translations = []
hindi_translations = []

for sentence in sentences:
    german = translator_de(sentence)[0]['translation_text']
    hindi = translator_hi(sentence)[0]['translation_text']

    german_translations.append(german)
    hindi_translations.append(hindi)

df["German"] = german_translations
df["Hindi"] = hindi_translations

df

,id,category,sentence_type,english_sentence,French,German,Hindi
0,1,News,Simple,The government announced a new education polic...,Le gouvernement a annoncé aujourd'hui une nouv...,Die Regierung kündigte heute eine neue Bildung...,सरकार ने आज एक नयी शिक्षा नीति घोषित की ।
1,2,News,Compound,The minister spoke to the media and explained ...,Le ministre s'est entretenu avec les médias et...,Der Minister sprach mit den Medien und erklärt...,पादरी ने मीडिया से बात की और नए सुधारों को समझ...
2,3,News,Complex,"Although the economy is growing, unemployment ...","Bien que l'économie se développe, le chômage d...","Obwohl die Wirtschaft wächst, bleibt die Arbei...","हालाँकि बेरोज़गारी बढ़ती जा रही है, फिर भी बेर..."
3,4,Social Media,Conversational,I just watched a great movie and I loved it.,Je viens de regarder un super film et j'ai adoré.,Ich habe mir gerade einen tollen Film angesehe...,मैं सिर्फ एक महान फिल्म देखा और मैं इसे प्यार ...
4,5,Social Media,Interrogative,Did you complete the assignment for NLP class?,Avez-vous terminé l'affectation pour la classe...,Hast du den Auftrag für den NLP-Kurs abgeschlo...,क्या आपने एनएलपी क्लास के लिए यह काम पूरा किया?
5,6,Social Media,Simple,Learning Python is fun and interesting.,Apprendre le python est amusant et intéressant.,Python zu lernen ist lustig und interessant.,पायथन सीखना मज़ेदार है और दिलचस्प है.
6,7,Academic,Technical,Machine learning models require large amounts ...,Les modèles d'apprentissage automatique nécess...,Maschinelle Lernmodelle erfordern große Datenm...,मशीन सीखने वाले मॉडलों के लिए बहुत मात्रा की आ...
7,8,Academic,Complex,"When neural networks are trained properly, the...",Lorsque les réseaux neuraux sont correctement ...,Wenn neuronale Netzwerke richtig ausgebildet w...,जब तंत्रिका नेटवर्क को सही तरीके से प्रशिक्षित...
8,9,Academic,Compound,Natural language processing is useful and it i...,Le traitement du langage naturel est utile et ...,Natürliche Sprachverarbeitung ist nützlich und...,स्वाभाविक भाषा बोलना उपयोगी है और यह मानव कंप्...
9,10,Conversation,Simple,Please close the door.,"Fermez la porte, s'il vous plaît.",Bitte schließen Sie die Tür.,कृपया दरवाजा बंद करो.
10,11,Conversation,Interrogative,Where are you going now?,Où vas-tu maintenant ?,Wo gehst du jetzt hin?,अब तुम कहाँ जा रहे हो?
11,12,Conversation,Compound,I will call you later and we can discuss the p...,Je vous appellerai plus tard et nous pourrons ...,Ich rufe dich später an und wir können das Pro...,मैं आपको बाद में फोन करेंगे और हम परियोजना पर ...
12,13,Technical,Technical,The transformer model uses attention mechanism...,Le modèle de transformateur utilise des mécani...,Das Transformatorenmodell nutzt Aufmerksamkeit...,ट्रांसलेटर मॉडल अनुवाद के लिए ध्यान संबंधी प्र...
13,14,Technical,Complex,"If the dataset is clean, the model will produc...","Si l'ensemble de données est propre, le modèle...","Wenn der Datensatz sauber ist, liefert das Mod...","अगर डेटासेट साफ है, तो मॉडल सही नतीजे पर पहुँच..."
14,15,Daily Life,Simple,I am going to the market.,Je vais au marché.,Ich gehe auf den Markt.,मैं बाजार के लिए जा रहा हूँ.
15,16,Daily Life,Interrogative,Can you help me with this problem?,Pouvez-vous m'aider avec ce problème ?,Können Sie mir bei diesem Problem helfen?,आप इस समस्या के साथ मेरी मदद कर सकते हैं?
16,17,Daily Life,Complex,"Even though it was raining, we went to college.","Même s'il pleuvait, nous sommes allés à l'univ...","Obwohl es regnete, gingen wir aufs College.","हालाँकि बारिश हो रही थी, फिर भी हम कॉलेज चले गए ।"
17,18,News,Technical,Scientists discovered a new satellite in space.,Les scientifiques ont découvert un nouveau sat...,Wissenschaftler entdeckten einen neuen Satelli...,वैज्ञानिकों ने अंतरिक्ष में एक नया उपग्रह खोज ...
18,19,Academic,Complex,"While studying NLP, students learn about token...","Tout en étudiant le NLP, les élèves apprennent...",Während des Studiums der NLP lernen die Schüle...,"नीपी का अध्ययन करते वक्‍त, विद्यार्थी सबूतों क..."
19,20,Conversation,Conversational,Let us meet tomorrow and finish the work.,Rendez-vous demain et finissons le travail.,Treffen wir uns morgen und beenden die Arbeit.,हमें कल मिलते हैं और काम खत्म करते हैं.

In [ ]:
df.to_csv("translated_output.csv", index=False)

print("File Saved Successfully")

File Saved Successfully

In [ ]:
from google.colab import files
files.download("translated_output.csv")

In [ ]:
complex_sentences = [
    "Although the economy is growing, unemployment remains a concern.",
    "When neural networks are trained properly, they perform better in prediction tasks.",
    "If the dataset is clean, the model will produce accurate results.",
    "Did you complete the assignment for NLP class?",
    "The transformer model uses attention mechanisms for translation."
]

for sentence in complex_sentences:
    print("English:", sentence)
    print("French:", translator_fr(sentence)[0]['translation_text'])
    print("German:", translator_de(sentence)[0]['translation_text'])
    print("Hindi:", translator_hi(sentence)[0]['translation_text'])
    print()

English: Although the economy is growing, unemployment remains a concern.
French: Bien que l'économie se développe, le chômage demeure un sujet de préoccupation.
German: Obwohl die Wirtschaft wächst, bleibt die Arbeitslosigkeit besorgniserregend.
Hindi: हालाँकि बेरोज़गारी बढ़ती जा रही है, फिर भी बेरोज़गारी की चिंता बढ़ती जा रही है ।

English: When neural networks are trained properly, they perform better in prediction tasks.
French: Lorsque les réseaux neuraux sont correctement formés, ils effectuent mieux dans les tâches de prédiction.
German: Wenn neuronale Netzwerke richtig ausgebildet werden, führen sie bessere Vorhersageaufgaben durch.
Hindi: जब तंत्रिका नेटवर्क को सही तरीके से प्रशिक्षित किया जाता है, तो वे भविष्यवाणी के कार्यों में बेहतर कार्य करते हैं ।

English: If the dataset is clean, the model will produce accurate results.
French: Si l'ensemble de données est propre, le modèle produira des résultats précis.
German: Wenn der Datensatz sauber ist, liefert das Modell genaue Ergebnisse.
Hindi: अगर डेटासेट साफ है, तो मॉडल सही नतीजे पर पहुँचा देगा ।

English: Did you complete the assignment for NLP class?
French: Avez-vous terminé l'affectation pour la classe NLP?
German: Hast du den Auftrag für den NLP-Kurs abgeschlossen?
Hindi: क्या आपने एनएलपी क्लास के लिए यह काम पूरा किया?

English: The transformer model uses attention mechanisms for translation.
French: Le modèle de transformateur utilise des mécanismes d'attention pour la traduction.
German: Das Transformatorenmodell nutzt Aufmerksamkeitsmechanismen für die Übersetzung.
Hindi: ट्रांसलेटर मॉडल अनुवाद के लिए ध्यान संबंधी प्रक्रिया प्रयोग करता है ।